name: ChristmasMobs
main: com.comze_instancelabs.christmasmobs.Main
version: 1.0.1
author: instancelabs
commands:
   spawnplayer:
      description: Spawn a christmas Player
      usage: /spawnplayer [name]
   spawnzombie:
      description: Spawn a christmas Zombie
      usage: /spawnzombie [name]
   removezombie:
      description: Remove a christmas Zombie
      usage: /removezombie
   spawnskeleton:
      description: Spawn a christmas skeleton
      usage: /spawnskeleton [name]
   removeskeleton:
      description: Remove a christmas skeleton
      usage: /removeskeleton