name: Weihnachtszombie
main: com.comze_instancelabs.zombie.Main
version: 1.0
author: instancelabs
commands:
   spawnzombie:
      description: Main command
      usage: /spawnzombie [name]
   removezombie:
      description: Main command
      usage: /removezombie [name]